package com.carbarn.inter.utils.qixiubao;

import java.util.HashMap;
import java.util.Map;

public class Contants {

//    public static final String url = "http://test-open-api2.0.nanxinwang.com//VinDecoder/decode";
//    public static final String secret = "c60e8d3539b3748e882ed3beb4ac3f6c";
//    public static final String appid = "7f5a424c687328576f337b0986dd14bd";

    public static final String vin_url = "http://open-api2.0.nanxinwang.com//VinDecoder/decode";
    public static final String vin_version = "4.6.0";
    public static final String secret = "533f15bd38980184203ada7b0fe029de";
    public static final String appid = "663f8c5be37ec1db7c6b38704c7a1c28";

    public static final String summary_url = "http://open-api2.0.nanxinwang.com//Bsm/summary";
    public static final String brand_url = "http://open-api2.0.nanxinwang.com/Bsm/brand";
    public static final String series_url = "http://open-api2.0.nanxinwang.com/Bsm/series";
    public static final String type_url = "http://open-api2.0.nanxinwang.com//Bsm/majorModel";
    public static final String type_detail_url = "http://open-api2.0.nanxinwang.com//Vehicle/getModelKeyValue";
    public static final String version = "1.0.1";
    public static final String version_type_detail = "1.0.0";

    public static Map<String, String> emission_standards = new HashMap<String, String>();
    public static Map<String, String> engines = new HashMap<String, String>();

    public static Map<String, String> type_of_cars = new HashMap<String, String>();

    public static Map<String, String> transmission = new HashMap<String, String>();

    public static Map<String, String> qixiubao_carbarn = new HashMap<String, String>();


    static{
        qixiubao_carbarn.put("双离合变速器(PDK)", "自动");
        qixiubao_carbarn.put("手动变速器(MT)", "手动");
        qixiubao_carbarn.put("无级变速器(E-CVT)", "自动");
        qixiubao_carbarn.put("双离合变速器", "自动");
        qixiubao_carbarn.put("三离合电驱变速器(AT)", "自动");
        qixiubao_carbarn.put("电动车单速变速器", "自动");
        qixiubao_carbarn.put("机械式自动变速器(AMT)", "自动");
        qixiubao_carbarn.put("双离合变速器(DSG)", "自动");
        qixiubao_carbarn.put("干式双离合变速器(DCT)", "自动");
        qixiubao_carbarn.put("固定齿比变速器", "自动");
        qixiubao_carbarn.put("序列变速器(AMT)", "自动");
        qixiubao_carbarn.put("序列变速器(RMT)", "自动");
        qixiubao_carbarn.put("双离合变速器(DCT)", "自动");
        qixiubao_carbarn.put("湿式双离合变速器(DCT)", "自动");
        qixiubao_carbarn.put("序列变速器(ISR)", "自动");
        qixiubao_carbarn.put("手自一体变速器(AMT)", "自动");
        qixiubao_carbarn.put("无级变速器(S-CVT)", "自动");
        qixiubao_carbarn.put("双离合变速器(TST)", "自动");
        qixiubao_carbarn.put("手自一体变速器(DSS)", "自动");
        qixiubao_carbarn.put("无级变速器(CVT)", "自动");
        qixiubao_carbarn.put("自动变速器(EDU)", "自动");
        qixiubao_carbarn.put("电子无级变速器(E-CVT)", "自动");
        qixiubao_carbarn.put("自动变速器(DHT)", "自动");
        qixiubao_carbarn.put("电子无级变速器(E-CVT)+自动变速器(AT)", "自动");
        qixiubao_carbarn.put("混合动力专用变速器(DHT)", "自动");
        qixiubao_carbarn.put("序列变速器(EMT)", "自动");
        qixiubao_carbarn.put("自动变速器(AT)", "自动");
        qixiubao_carbarn.put("手自一体变速器(AT)", "自动");
        qixiubao_carbarn.put("国III", "国三");
        qixiubao_carbarn.put("欧V", "欧五");
        qixiubao_carbarn.put("国IV(国V)", "国四");
        qixiubao_carbarn.put("欧IV", "欧六");
        qixiubao_carbarn.put("欧VI", "欧四");
        qixiubao_carbarn.put("国IV/国V", "国四");
        qixiubao_carbarn.put("欧III+OBD", "欧三");
        qixiubao_carbarn.put("欧I", "欧一");
        qixiubao_carbarn.put("欧III", "欧三");
        qixiubao_carbarn.put("欧II", "欧二");
        qixiubao_carbarn.put("国IV/京V", "国四");
        qixiubao_carbarn.put("国II", "国二");
        qixiubao_carbarn.put("国VIB", "国六");
        qixiubao_carbarn.put("国IV+OBD", "国四");
        qixiubao_carbarn.put("欧IV+OBD", "欧四");
        qixiubao_carbarn.put("京V", "其他");
        qixiubao_carbarn.put("国I", "国一");
        qixiubao_carbarn.put("国IV", "国四");
        qixiubao_carbarn.put("国IV(国V)+OBD", "国四");
        qixiubao_carbarn.put("国V+OBD", "国五");
        qixiubao_carbarn.put("国V", "国五");
        qixiubao_carbarn.put("国VI", "国六");
        qixiubao_carbarn.put("国IV(京V)", "国四");
        qixiubao_carbarn.put("国V(国VI)", "国五");
        qixiubao_carbarn.put("国III+OBD", "国三");
        qixiubao_carbarn.put("欧V+OBD", "欧五");
        qixiubao_carbarn.put("汽油+24V轻混系统", "汽油");
        qixiubao_carbarn.put("汽油(汽油电驱)", "汽油");
        qixiubao_carbarn.put("压缩天然气(CNG)", "其它");
        qixiubao_carbarn.put("汽油/乙醇", "汽油");
        qixiubao_carbarn.put("汽油+48V轻混系统", "汽油");
        qixiubao_carbarn.put("柴油", "柴油");
        qixiubao_carbarn.put("纯电动", "电动");
        qixiubao_carbarn.put("汽油/CNG", "汽油");
        qixiubao_carbarn.put("液化石油气(LPG)", "其它");
        qixiubao_carbarn.put("汽油+90V轻混系统", "汽油");
        qixiubao_carbarn.put("柴油(油电混合)", "混动");
        qixiubao_carbarn.put("汽油/LPG", "汽油");
        qixiubao_carbarn.put("甲醇混动", "混动");
        qixiubao_carbarn.put("汽油", "汽油");
        qixiubao_carbarn.put("汽油/NG", "汽油");
        qixiubao_carbarn.put("插电式混合动力", "混动");
        qixiubao_carbarn.put("汽油/LNG/CNG", "汽油");
        qixiubao_carbarn.put("汽油(油电混合)", "混动");
        qixiubao_carbarn.put("甲醇", "其它");
        qixiubao_carbarn.put("汽油(增程式)", "混动");
        qixiubao_carbarn.put("氢燃料", "其它");
        qixiubao_carbarn.put("柴油+48V轻混系统", "柴油");
        qixiubao_carbarn.put("前置+后置四驱", "四驱");
        qixiubao_carbarn.put("前置四驱", "四驱");
        qixiubao_carbarn.put("中置四驱", "四驱");
        qixiubao_carbarn.put("两驱", "两驱");
        qixiubao_carbarn.put("双电机四驱", "四驱");
        qixiubao_carbarn.put("中置", "前驱");
        qixiubao_carbarn.put("后驱", "后驱");
        qixiubao_carbarn.put("后置四驱", "四驱");
        qixiubao_carbarn.put("后置", "后驱");
        qixiubao_carbarn.put("前置", "前驱");
        qixiubao_carbarn.put("前驱", "前驱");
        qixiubao_carbarn.put("前置后驱", "后驱");
        qixiubao_carbarn.put("中置后驱", "后驱");
        qixiubao_carbarn.put("前置前驱", "前驱");
        qixiubao_carbarn.put("中置前驱", "前驱");
        qixiubao_carbarn.put("三电机四驱", "四驱");
        qixiubao_carbarn.put("双电机后驱", "后驱");
        qixiubao_carbarn.put("四驱", "四驱");
        qixiubao_carbarn.put("后置后驱", "后驱");
        qixiubao_carbarn.put("四电机四驱", "四驱");
        qixiubao_carbarn.put("紧凑型SUV", "越野车/SUV");
        qixiubao_carbarn.put("跑车", "轿跑车");
        qixiubao_carbarn.put("紧凑型车", "轿车");
        qixiubao_carbarn.put("房车", "房车");
        qixiubao_carbarn.put("大型SUV", "越野车/SUV");
        qixiubao_carbarn.put("小型车", "轿车");
        qixiubao_carbarn.put("MPV", "商务车/MPV");
        qixiubao_carbarn.put("SUV", "越野车/SUV");
        qixiubao_carbarn.put("轿车", "轿车");
        qixiubao_carbarn.put("轻客", "客车");
        qixiubao_carbarn.put("轻卡", "货车");
        qixiubao_carbarn.put("微卡", "货车");
        qixiubao_carbarn.put("微面", "面包车");
        qixiubao_carbarn.put("皮卡", "皮卡");
        qixiubao_carbarn.put("轻货", "货车");

        qixiubao_carbarn.put("国I", "国一");
        qixiubao_carbarn.put("国II", "国二");
        qixiubao_carbarn.put("国III", "国三");
        qixiubao_carbarn.put("国IV", "国四");
        qixiubao_carbarn.put("国IV(国V)", "国四");
        qixiubao_carbarn.put("国IV(国V)+OBD", "国四");
        qixiubao_carbarn.put("国IV(京V)", "国四");
        qixiubao_carbarn.put("国IV/国V", "国四");
        qixiubao_carbarn.put("国IV/京V", "国四");
        qixiubao_carbarn.put("国IV+OBD", "国四");
        qixiubao_carbarn.put("国V", "国五");
        qixiubao_carbarn.put("国V(国VI)", "国五");
        qixiubao_carbarn.put("国V+OBD", "国五");
        qixiubao_carbarn.put("京V", "国五");
        qixiubao_carbarn.put("国VI", "国六");
        qixiubao_carbarn.put("国VIB", "国六");
        qixiubao_carbarn.put("欧I", "欧一");
        qixiubao_carbarn.put("欧II", "欧二");
        qixiubao_carbarn.put("欧III", "欧三");
        qixiubao_carbarn.put("欧III+OBD", "欧三");
        qixiubao_carbarn.put("欧IV", "欧四");
        qixiubao_carbarn.put("欧IV+OBD", "欧四");

        qixiubao_carbarn.put("汽油","汽油");
        qixiubao_carbarn.put("柴油","柴油");
        qixiubao_carbarn.put("混动","混动");
        qixiubao_carbarn.put("电动","电动");

//        qixiubao_carbarn.put("MPV","商务车/MPV");
//        qixiubao_carbarn.put("SUV","越野车/SUV");
//        qixiubao_carbarn.put("大型SUV","越野车/SUV");
//        qixiubao_carbarn.put("房车","房车");
//        qixiubao_carbarn.put("轿车","轿车");
//        qixiubao_carbarn.put("紧凑型SUV","越野车/SUV");
//        qixiubao_carbarn.put("紧凑型车","轿车");
//        qixiubao_carbarn.put("跑车","跑车");
//        qixiubao_carbarn.put("皮卡","皮卡");
//        qixiubao_carbarn.put("轻货","货车");
//        qixiubao_carbarn.put("轻卡","皮卡");
//        qixiubao_carbarn.put("轻客","客车");
//        qixiubao_carbarn.put("微卡","皮卡");
//        qixiubao_carbarn.put("微面","面包车");
//        qixiubao_carbarn.put("小型车","轿车");

        qixiubao_carbarn.put("10挡手动","手动");
        qixiubao_carbarn.put("10挡手自一体","自动");
        qixiubao_carbarn.put("10挡无级变速","自动");
        qixiubao_carbarn.put("10挡自动","自动");
        qixiubao_carbarn.put("12挡手动","手动");
        qixiubao_carbarn.put("12挡手自一体","自动");
        qixiubao_carbarn.put("12挡自动","自动");
        qixiubao_carbarn.put("13挡手动","手动");
        qixiubao_carbarn.put("14挡手动","手动");
        qixiubao_carbarn.put("14挡手自一体","自动");
        qixiubao_carbarn.put("16挡手动","手动");
        qixiubao_carbarn.put("16挡手自一体","自动");
        qixiubao_carbarn.put("16挡自动","自动");
        qixiubao_carbarn.put("1挡DHT","自动");
        qixiubao_carbarn.put("1挡单速","自动");
        qixiubao_carbarn.put("1挡电动车单速","自动");
        qixiubao_carbarn.put("2挡DHT","自动");
        qixiubao_carbarn.put("2挡自动","自动");
        qixiubao_carbarn.put("3挡DHT","自动");
        qixiubao_carbarn.put("3挡自动","自动");
        qixiubao_carbarn.put("4挡DHT","自动");
        qixiubao_carbarn.put("4挡手动","手动");
        qixiubao_carbarn.put("4挡手自一体","自动");
        qixiubao_carbarn.put("4挡无级变速","自动");
        qixiubao_carbarn.put("4挡自动","自动");
        qixiubao_carbarn.put("5挡AMT","自动");
        qixiubao_carbarn.put("5挡半自动","自动");
        qixiubao_carbarn.put("5挡湿式双离合","自动");
        qixiubao_carbarn.put("5挡手动","手动");
        qixiubao_carbarn.put("5挡手自一体","自动");
        qixiubao_carbarn.put("5挡双离合","自动");
        qixiubao_carbarn.put("5挡无级/手动一体式","自动");
        qixiubao_carbarn.put("5挡序列","手动");
        qixiubao_carbarn.put("5挡自动","自动");
        qixiubao_carbarn.put("6挡AMT","自动");
        qixiubao_carbarn.put("6挡DSG","自动");
        qixiubao_carbarn.put("6挡半自动","自动");
        qixiubao_carbarn.put("6挡干式双离合","自动");
        qixiubao_carbarn.put("6挡连续手自一体","自动");
        qixiubao_carbarn.put("6挡三离合电驱变速器","自动");
        qixiubao_carbarn.put("6挡湿式双离合","自动");
        qixiubao_carbarn.put("6挡手动","手动");
        qixiubao_carbarn.put("6挡手自一体","自动");
        qixiubao_carbarn.put("6挡双离合","自动");
        qixiubao_carbarn.put("6挡无级/手动一体式","自动");
        qixiubao_carbarn.put("6挡无级变速","自动");
        qixiubao_carbarn.put("6挡序列","手动");
        qixiubao_carbarn.put("6挡序列变速","手动");
        qixiubao_carbarn.put("6挡序列变速箱(AMT)","自动");
        qixiubao_carbarn.put("6挡自动","自动");
        qixiubao_carbarn.put("7挡AMT","自动");
        qixiubao_carbarn.put("7挡DSG","自动");
        qixiubao_carbarn.put("7挡ISR变速箱","自动");
        qixiubao_carbarn.put("7挡干式双离合","自动");
        qixiubao_carbarn.put("7挡湿式双离合","自动");
        qixiubao_carbarn.put("7挡手动","手动");
        qixiubao_carbarn.put("7挡手自一体","自动");
        qixiubao_carbarn.put("7挡双离合","自动");
        qixiubao_carbarn.put("7挡无级变速","自动");
        qixiubao_carbarn.put("7挡序列","手动");
        qixiubao_carbarn.put("7挡自动","自动");
        qixiubao_carbarn.put("8挡湿式双离合","自动");
        qixiubao_carbarn.put("8挡手动","手动");
        qixiubao_carbarn.put("8挡手自一体","自动");
        qixiubao_carbarn.put("8挡双离合变速箱","自动");
        qixiubao_carbarn.put("8挡自动","自动");
        qixiubao_carbarn.put("9挡湿式双离合","自动");
        qixiubao_carbarn.put("9挡手动","手动");
        qixiubao_carbarn.put("9挡手自一体","自动");
        qixiubao_carbarn.put("9挡自动","自动");
        qixiubao_carbarn.put("AMT（组合10挡）","自动");
        qixiubao_carbarn.put("CVT无级变速","自动");
        qixiubao_carbarn.put("CVT无级变速(模拟10挡)","自动");
        qixiubao_carbarn.put("CVT无级变速(模拟4挡)","自动");
        qixiubao_carbarn.put("CVT无级变速(模拟5挡)","自动");
        qixiubao_carbarn.put("CVT无级变速(模拟6挡)","自动");
        qixiubao_carbarn.put("CVT无级变速(模拟7挡)","自动");
        qixiubao_carbarn.put("CVT无级变速(模拟7挡）","自动");
        qixiubao_carbarn.put("CVT无级变速(模拟8挡)","自动");
        qixiubao_carbarn.put("CVT无级变速(模拟9挡)","自动");
        qixiubao_carbarn.put("CVT无级变速模拟7挡","自动");
        qixiubao_carbarn.put("DHT","自动");
        qixiubao_carbarn.put("ECVT","自动");
        qixiubao_carbarn.put("E-CVT+自动变速箱（模拟10挡）","自动");
        qixiubao_carbarn.put("E-CVT+自动变速箱(模拟10挡)","自动");
        qixiubao_carbarn.put("E-CVT无级变速","自动");
        qixiubao_carbarn.put("电动车单速","自动");
        qixiubao_carbarn.put("电动车单速变速箱","自动");
        qixiubao_carbarn.put("电动车单速变速箱（模拟5挡）","自动");
        qixiubao_carbarn.put("电子无级变速","自动");
        qixiubao_carbarn.put("模拟10挡挡自动","自动");
        qixiubao_carbarn.put("模拟6挡挡自动","自动");
        qixiubao_carbarn.put("模拟6档挡自动","自动");
        qixiubao_carbarn.put("模拟7挡挡自动","自动");
        qixiubao_carbarn.put("模拟7档挡自动","自动");
        qixiubao_carbarn.put("模拟8挡挡自动","自动");
        qixiubao_carbarn.put("模拟8档挡自动","自动");
        qixiubao_carbarn.put("模拟9档挡自动","自动");
        qixiubao_carbarn.put("手动","手动");
        qixiubao_carbarn.put("手自一体","自动");
        qixiubao_carbarn.put("无级/手动一体式","自动");
        qixiubao_carbarn.put("无级变速","自动");
        qixiubao_carbarn.put("自动","自动");

    }
}
