spring:
  profiles:
    active: prod
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        max-active: 16
        max-wait: 3000

sa-token:
  token-name: satoken
  timeout: 2592000
  is-redis: true


mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/im/*.xml
  type-aliases-package: com.carbarn.*.pojo
